NEOS-1692:add in transform uuid transformer
nucleuscloud/neosync pull request #3079
Opened 2024-12-23 21:43 UTC by evisdrenova

2025-01-02 17:39 UTC, nickzelei requested changes
Left a few comments regarding the algorithm for transforming the uuids

2025-01-02 17:39 UTC, nickzelei commented on worker/pkg/benthos/transformers/transform_uuid.go
> +	output := uuid.NewSHA1(uuid.Nil, seedBytes).String()
Do we actually want to put all of the generated uuids in the same Nil namespace? 
The original design we came up with puts the new uuids inside of the original uuid's namespace.

2025-01-02 17:39 UTC, nickzelei commented on worker/pkg/benthos/transformers/transform_uuid.go
> +	binary.LittleEndian.PutUint64(seedBytes[8:], uint64(randomInt))
Curious as to why we are going through this whole song and dance to generate the input data when it accepts any arbitrary amount.

In other words, why not just `uuid.NewSha1(inputUuid, []byte(randomizer.Float64()))`

2025-01-02 17:39 UTC, nickzelei commented on worker/pkg/benthos/transformers/transform_uuid_test.go
> +	fmt.Println("test", checkVars)
I don't think we want this here. If you want to have a test log something, use the test logger `t.Log` - then it will only show up when running go tests in verbose mode.

2025-01-02 21:01 UTC, evisdrenova commented on worker/pkg/benthos/transformers/transform_uuid.go
> +	output := uuid.NewSHA1(uuid.Nil, seedBytes).String()
updated

2025-01-02 21:02 UTC, evisdrenova commented on worker/pkg/benthos/transformers/transform_uuid_test.go
> +	fmt.Println("test", checkVars)
ah good catch - that was hold over from testing

2025-01-02 21:06 UTC, evisdrenova commented on worker/pkg/benthos/transformers/transform_uuid.go
> +	binary.LittleEndian.PutUint64(seedBytes[8:], uint64(randomInt))
we could do that too

2025-01-03 19:21 UTC, nickzelei commented on worker/pkg/benthos/transformers/transform_uuid.go
> +	binary.LittleEndian.PutUint64(bytes, uint64(randomInt))
If you go into the randomizer you can expose the `Int63` function, then the `Float64` can just go away entirely.

Then it can become `uuid.NewSHA1(inputUuid, []byte(randomizer.Int63()))`

2025-01-06 20:03 UTC, nickzelei approved these changes

2025-01-06 20:04 UTC, merged